# Generated by Django 4.2.6 on 2023-11-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=26)),
                ("first_name", models.CharField(max_length=26)),
                ("title", models.CharField(blank=True, max_length=16)),
                (
                    "img",
                    models.ImageField(blank=True, upload_to="board_members"),
                ),
            ],
            options={
                "verbose_name": "Board Member",
                "verbose_name_plural": "Board Members",
            },
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=26)),
                ("first_name", models.CharField(max_length=26)),
                ("profile", models.TextField()),
                ("title", models.CharField(blank=True, max_length=32)),
                ("slug", models.SlugField(null=True)),
                ("img", models.ImageField(blank=True, upload_to="coaches")),
            ],
            options={
                "verbose_name": "Coach",
                "verbose_name_plural": "Coaches",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("teaser", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=50)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("testimonial", models.TextField()),
                (
                    "img",
                    models.ImageField(blank=True, upload_to="testimonials"),
                ),
            ],
        ),
    ]
