# Generated by Django 4.2.6 on 2024-11-15 22:30
from django.db import migrations
from django.utils.text import slugify


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    def create_event_categories(apps, schema_editor):
        EventCategory = apps.get_model('website', 'EventCategory')

        categories = [
            ("Aroostook Athletics", "gray"),
            ("Membership Event", "red"),
            ("Community Event", "yellow"),
            ("US Biathlon Association", "green"),
            ("Jalbert Program", "blue"),
            ("Training Camp", "purple"),
        ]

        for name, color in categories:
            EventCategory.objects.create(
                name=name,
                color=color,
                slug=slugify(name),
            )

    def delete_event_categories(apps, schema_editor):
        EventCategory = apps.get_model('website', 'EventCategory')

        category_names = [
            "Aroostook Athletics",
            "Membership Event",
            "Community Event",
            "US Biathlon Association",
            "Jalbert Program",
            "Training Camp",
        ]

        EventCategory.objects.filter(name__in=category_names).delete()

    operations = [
        migrations.RunPython(create_event_categories, delete_event_categories),
    ]
