# Generated by Django 5.0.3 on 2025-03-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventpage",
            old_name="image",
            new_name="banner_image",
        ),
        migrations.AddField(
            model_name="eventpage",
            name="pdf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
    ]
