# Generated by Django 4.2.6 on 2025-03-27 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="main_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
