# Generated by Django 5.0.3 on 2025-03-27 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("website", "0002_rename_image_eventpage_banner_image_eventpage_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
