# Generated by Django 4.2.6 on 2023-11-15 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("website", "0002_remove_boardmember_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardmember",
            name="img",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
