# Generated by Django 4.2.6 on 2025-03-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_homepage_main_content_homepage_main_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="main_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
