# Generated by Django 5.0.3 on 2025-03-28 23:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_daypasslink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daypasslink",
            name="image",
        ),
    ]
