# Generated by Django 4.2.6 on 2023-11-15 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("website", "0006_eventpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="banner_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Banner Image",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="location",
            field=models.CharField(
                choices=[
                    ("fkoc_lodge", "Fort Kent Outdoor Center Lodge"),
                    ("wax_building", "Fort Kent Outdoor Center Wax Building"),
                    ("stadium", "Fort Kent Outdoor Center Stadium"),
                ],
                max_length=50,
            ),
        ),
    ]
