# Generated by Django 5.0.3 on 2025-03-29 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("website", "0007_daypasslink_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="cta_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="cta_text",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
