# Generated by Django 4.2.6 on 2024-12-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_alter_event_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, to="website.eventtag"
            ),
        ),
    ]
