# Generated by Django 4.2.6 on 2023-11-15 01:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_eventpage_banner_image_alter_eventpage_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coach",
            name="img",
        ),
    ]
