# Generated by Django 4.2.6 on 2024-12-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_alter_event_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hide_from_event_list",
            field=models.BooleanField(default=False),
        ),
    ]
