# Generated by Django 4.2.6 on 2024-12-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_event_hide_from_event_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="pdf_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
