# Generated by Django 4.2.6 on 2025-03-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_remove_event_hide_from_event_list_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("biography", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
