# Generated by Django 4.2.6 on 2025-04-27 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_aboutuspage_fall_banner_opacity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="fall_banner_image",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="fall_banner_opacity",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="spring_banner_image",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="spring_banner_opacity",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="summer_banner_image",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="summer_banner_opacity",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="winter_banner_image",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="winter_banner_opacity",
        ),
    ]
