# Generated by Django 4.2.6 on 2025-07-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_mapcategory_trailspage_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="title",
            field=models.CharField(default="MAP", max_length=100),
            preserve_default=False,
        ),
    ]
