# Generated by Django 4.2.6 on 2023-11-18 13:18

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0014_rename_category_eventcategory_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="tags",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="website.eventtags"
            ),
        ),
    ]
