# Generated by Django 4.2.6 on 2025-07-20 03:17

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0001_squashed_0014_event_map_mapcategory_trailspage_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsession",
            name="event",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="website.event",
            ),
        ),
    ]
