# Generated by Django 4.2.6 on 2025-07-19 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_map_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="map",
            options={},
        ),
        migrations.RemoveField(
            model_name="map",
            name="page",
        ),
        migrations.RemoveField(
            model_name="map",
            name="sort_order",
        ),
        migrations.DeleteModel(
            name="TrailsPage",
        ),
    ]
