# Generated by Django 4.2.6 on 2023-11-18 13:23

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0015_alter_eventpage_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventcategory",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="eventtags",
            old_name="title",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="website.eventcategory",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="tags",
            field=modelcluster.fields.ParentalManyToManyField(
                to="website.eventtags"
            ),
        ),
    ]
