# Generated by Django 5.2.4 on 2025-07-23 23:46

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_eventsession_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daypasslink',
            name='background_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='cta_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='main_content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
