# Generated by Django 4.2.6 on 2025-07-19 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0016_alter_map_options_remove_map_page_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmember",
            options={},
        ),
        migrations.RemoveField(
            model_name="boardmember",
            name="page",
        ),
        migrations.RemoveField(
            model_name="boardmember",
            name="sort_order",
        ),
    ]
