# Generated by Django 4.2.6 on 2025-07-19 02:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0017_alter_boardmember_options_remove_boardmember_page_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coach",
            options={},
        ),
        migrations.RemoveField(
            model_name="coach",
            name="page",
        ),
        migrations.RemoveField(
            model_name="coach",
            name="sort_order",
        ),
    ]
