# Generated by Django 5.2.4 on 2025-08-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_homepage_cta_page_2_homepage_cta_text_2_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutUsPage",
        ),
    ]
