# Generated by Django 5.2.4 on 2025-08-14 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_delete_aboutuspage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SummerActivity",
        ),
        migrations.DeleteModel(
            name="WinterActivity",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.DeleteModel(
            name="ActivitiesPage",
        ),
        migrations.DeleteModel(
            name="DayPassesPage",
        ),
        migrations.DeleteModel(
            name="LegacyPage",
        ),
        migrations.DeleteModel(
            name="ProgramsPage",
        ),
        migrations.DeleteModel(
            name="TrailsPage",
        ),
        migrations.DeleteModel(
            name="UpcomingListingPage",
        ),
    ]
