# Generated by Django 4.2.6 on 2025-07-19 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0019_alter_activity_options_alter_coach_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="daypasslink",
            options={},
        ),
        migrations.RemoveField(
            model_name="daypasslink",
            name="page",
        ),
        migrations.RemoveField(
            model_name="daypasslink",
            name="sort_order",
        ),
    ]
