# Generated by Django 5.2.4 on 2025-08-14 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_remove_summeractivity_page_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomePage",
        ),
    ]
