# Generated by Django 5.2.4 on 2025-12-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0020_delete_homepage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DayPassLink",
        ),
    ]
