# Generated by Django 4.2.6 on 2025-07-19 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0020_alter_daypasslink_options_remove_daypasslink_page_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventsession",
            name="page",
        ),
        migrations.DeleteModel(
            name="EventPage",
        ),
        migrations.DeleteModel(
            name="EventSession",
        ),
    ]
