# Generated by Django 4.2.6 on 2023-11-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0021_alter_eventcategory_color_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="teaser",
            field=models.CharField(max_length=200),
        ),
    ]
