# Generated by Django 4.2.6 on 2023-11-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0022_alter_eventpage_teaser"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Leave blank if event is only one day.",
                null=True,
            ),
        ),
    ]
