# Generated by Django 4.2.6 on 2025-07-19 12:43

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0022_event_eventsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsession",
            name="event",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="website.event",
            ),
        ),
    ]
