# Generated by Django 4.2.6 on 2023-11-18 16:40

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0026_remove_eventpage_date_remove_eventpage_end_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("date", models.DateField(verbose_name="Event Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="End Time"
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalManyToManyField(
                        related_name="dates", to="website.eventpage"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
