# Generated by Django 4.2.6 on 2023-11-18 20:32

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0027_eventdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventdate",
            name="page",
        ),
        migrations.AddField(
            model_name="eventdate",
            name="page",
            field=modelcluster.fields.ParentalKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dates",
                to="website.eventpage",
            ),
        ),
    ]
