# Generated by Django 4.2.6 on 2023-11-18 21:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0028_remove_eventdate_page_eventdate_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="body",
        ),
    ]
