# Generated by Django 4.2.6 on 2023-11-19 00:03

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("website", "0031_alter_eventpage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "default_cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text", required=True
                                    ),
                                ),
                                (
                                    "cta_1",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA 1",
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_2",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA 2",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "left_header_paragraph_two_image_right",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text", required=True
                                    ),
                                ),
                                (
                                    "image_left",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Left Image", required=True
                                    ),
                                ),
                                (
                                    "image_right",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Right Image", required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
