# Generated by Django 4.2.6 on 2023-11-19 14:02

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0043_alter_boardmember_options_alter_boardmember_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="page",
            field=modelcluster.fields.ParentalKey(
                default=11,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coaches",
                to="website.programpage",
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
