# Generated by Django 4.2.6 on 2023-11-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0044_coach_page_coach_sort_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="title",
            field=models.CharField(max_length=32),
        ),
    ]
