# Generated by Django 4.2.6 on 2023-11-20 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("website", "0047_activitypage_winteractivity_threeseasonactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitypage",
            name="card_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Display Image",
            ),
        ),
        migrations.AlterField(
            model_name="activitypage",
            name="card_image_hover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Hover Image",
            ),
        ),
    ]
