# Generated by Django 4.2.6 on 2023-11-20 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("website", "0048_alter_activitypage_card_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitypage",
            name="banner_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Banner Image",
            ),
        ),
        migrations.AlterField(
            model_name="activitypage",
            name="card_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Display Image",
            ),
        ),
        migrations.AlterField(
            model_name="activitypage",
            name="card_image_hover",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Hover Image",
            ),
        ),
    ]
