# Generated by Django 4.2.6 on 2023-11-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0050_remove_activitypage_card_image_hover"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitypage",
            name="col_span",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
