# Generated by Django 4.2.6 on 2023-12-02 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("website", "0054_delete_sponsorlogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershippage",
            name="membership_pdf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
    ]
