# Generated by Django 4.2.6 on 2023-12-10 17:48

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0055_membershippage_membership_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayPassSquareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", wagtail.fields.RichTextField()),
                ("link", models.URLField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="square_links",
                        to="website.daypasspage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Square Link",
                "verbose_name_plural": "Square Links",
                "ordering": ["sort_order"],
            },
        ),
    ]
