# Generated by Django 4.2.6 on 2023-12-10 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("website", "0056_daypasssquarelink"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daypasssquarelink",
            name="description",
        ),
        migrations.AddField(
            model_name="daypasssquarelink",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Display Image",
            ),
        ),
    ]
