# Generated by Django 4.2.6 on 2023-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0057_remove_daypasssquarelink_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="daypasssquarelink",
            name="fee",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
