# Generated by Django 4.2.6 on 2023-12-15 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("website", "0059_daypasspage_show_support_image_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="flyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
                verbose_name="Flyer",
            ),
        ),
    ]
