# Generated by Django 4.2.6 on 2023-12-15 22:58

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0061_homepage_body_alter_eventpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "default_cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text", required=True
                                    ),
                                ),
                                (
                                    "cta_1",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA 1",
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_2",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA 2",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "left_header_paragraph_two_image_right",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text", required=True
                                    ),
                                ),
                                (
                                    "image_left",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Left Image", required=True
                                    ),
                                ),
                                (
                                    "image_right",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Right Image", required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "visual_image_with_header",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text", required=True
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Image", required=True
                                    ),
                                ),
                                (
                                    "cta_1",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA 1",
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_2",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA 2",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "default_cta",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text", required=True
                                    ),
                                ),
                                (
                                    "cta_1",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA 1",
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_2",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA 2",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "left_header_paragraph_two_image_right",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text", required=True
                                    ),
                                ),
                                (
                                    "image_left",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Left Image", required=True
                                    ),
                                ),
                                (
                                    "image_right",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Right Image", required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "visual_image_with_header",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        label="Heading", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text", required=True
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Image", required=True
                                    ),
                                ),
                                (
                                    "cta_1",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA 1",
                                        required=False,
                                    ),
                                ),
                                (
                                    "cta_2",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    label="Text",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "page",
                                                wagtail.blocks.PageChooserBlock(
                                                    label="Link",
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA 2",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
