# Generated by Django 4.2.6 on 2023-12-23 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("website", "0063_alter_eventpage_body_alter_homepage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDatePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Event Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                (
                    "end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="End Time"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
