# Generated by Django 4.2.6 on 2023-12-24 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0064_eventdatepage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventDate",
        ),
    ]
