# Generated by Django 4.2.6 on 2023-12-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0065_delete_eventdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="location",
            field=models.CharField(
                choices=[
                    ("fkoc_lodge", "Fort Kent Outdoor Center Lodge"),
                    ("wax_building", "Fort Kent Outdoor Center Wax Building"),
                    ("stadium", "Fort Kent Outdoor Center Stadium"),
                    ("parking_lot", "Fort Kent Outdoor Center Parking Lot"),
                ],
                max_length=50,
            ),
        ),
    ]
