# Generated by Django 4.2.6 on 2023-12-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0066_alter_eventpage_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventdatepage",
            name="canceled",
            field=models.BooleanField(default=False),
        ),
    ]
