# Generated by Django 4.2.6 on 2023-12-24 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0067_eventdatepage_canceled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventdatepage",
            old_name="canceled",
            new_name="cancelled",
        ),
    ]
