# Generated by Django 4.2.6 on 2024-02-04 03:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0068_rename_canceled_eventdatepage_cancelled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmember",
            options={
                "verbose_name": "Board Member",
                "verbose_name_plural": "Board Members",
            },
        ),
        migrations.RemoveField(
            model_name="boardmember",
            name="sort_order",
        ),
    ]
