# Generated by Django 4.2.6 on 2024-02-04 03:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0069_alter_boardmember_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boardmember",
            name="page",
        ),
    ]
