# Generated by Django 4.2.6 on 2024-02-04 04:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0070_remove_boardmember_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="facilitypage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="locationpage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="policiespage",
            name="page_ptr",
        ),
        migrations.RemoveField(
            model_name="rentalspage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="Testimonial",
        ),
        migrations.RemoveField(
            model_name="trailspage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="AboutPage",
        ),
        migrations.DeleteModel(
            name="FacilityPage",
        ),
        migrations.DeleteModel(
            name="LocationPage",
        ),
        migrations.DeleteModel(
            name="PoliciesPage",
        ),
        migrations.DeleteModel(
            name="RentalsPage",
        ),
        migrations.DeleteModel(
            name="TrailsPage",
        ),
    ]
