repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.11.2
-   repo: https://gitlab.com/pycqa/flake8
    rev: stable
    hooks:
    - id: flake8
