# Generated by Django 4.2.6 on 2023-11-11 21:44

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=26)),
                ("first_name", models.CharField(max_length=26)),
                ("title", models.CharField(blank=True, max_length=16)),
                ("img_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=26)),
                ("first_name", models.CharField(max_length=26)),
                ("profile", models.TextField()),
                ("title", models.CharField(blank=True, max_length=16)),
                ("img_url", models.URLField(blank=True)),
                ("slug", models.SlugField(null=True)),
            ],
            options={
                "verbose_name_plural": "Coaches",
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("testimonial", models.TextField()),
                ("img_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("event_date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("fkoc_arena", "FKOC Arena"),
                            ("fkoc_lodge", "FKOC Lodge"),
                            ("fkoc_wax_building", "FKOC Wax Building"),
                        ],
                        default="fkoc_lodge",
                        max_length=17,
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "images_with_heading_and_description",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "heading",
                                            wagtail.blocks.CharBlock(
                                                label="Heading", required=True
                                            ),
                                        ),
                                        (
                                            "text",
                                            wagtail.blocks.CharBlock(
                                                label="Text", required=True
                                            ),
                                        ),
                                        (
                                            "image_left",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Left Image",
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "image_right",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                label="Right Image",
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "banner_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
