# Generated by Django 4.2.6 on 2023-11-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=26)),
                ("first_name", models.CharField(max_length=26)),
                ("title", models.CharField(blank=True, max_length=16)),
                ("img_url", models.URLField(blank=True)),
            ],
        ),
    ]
