# Generated by Django 4.2.6 on 2023-11-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmember",
            name="img_url",
            field=models.ImageField(upload_to=""),
        ),
    ]
