# Generated by Django 4.2.6 on 2023-11-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_auto_20231105_1241"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=26)),
                ("first_name", models.CharField(max_length=26)),
                ("profile", models.TextField()),
                ("title", models.CharField(blank=True, max_length=16)),
                ("img_url", models.URLField(blank=True)),
                ("slug", models.SlugField(null=False, unique=True, max_length=50))
            ],
        ),
    ]
