# Generated by Django 4.2.6 on 2023-11-12 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_boardmember_img_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="boardmember",
            old_name="img_url",
            new_name="img",
        ),
    ]
