# Generated by Django 4.2.6 on 2023-11-12 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_rename_img_url_boardmember_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardmember",
            name="img",
            field=models.ImageField(blank=True, upload_to="board_members"),
        ),
    ]
