# Generated by Django 4.2.6 on 2023-11-12 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_whowearepage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoardMember",
        ),
    ]
