# Generated by Django 4.2.6 on 2023-11-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_auto_20231105_1409"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=50)),
                ("testimonial", models.TextField()),
                ("img_url", models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="coach",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
