# Generated by Django 4.2.6 on 2023-11-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_boardmember_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coach",
            name="title",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
