# Generated by Django 4.2.6 on 2023-11-12 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_alter_coach_title"),
    ]

    def populate_coaching_staff(apps, schema_editor):
        Coach = apps.get_model('website', 'Coach')
        carl = Coach(
            last_name="Theriault",
            first_name="Carl",
            title="Program Director",
            img_url="https:////cdn.fortkentoc.org/programs/coach_photos/fort-kent-outdoor-center-coach-carl-theriault.jpg",
            profile="Carl has been involved with coaching skiing and biathlon for the past 23 years, and is a life long lover of anything you can do on skis! Coordinating training programs, range activities, FKOC development, and the local High School Nordic team fill most his days. When he is not working on ski programs and activities, you can find Carl out traveling, or riding horses, bicycles, and motorcycles."
        )
        carl.save()
        matt = Coach(
            last_name="Michaud",
            first_name="Matt",
            title="Youth and Masters Biathlon Coach",
            img_url="https://cdn.fortkentoc.org/programs/coach_photos/fort-kent-outdoor-center-coach-matt-michaud.jpg",
            profile="An active skier all his life, Matt spent several years as part of the National Guard Biathlon team, and now focuses on volunteering to help us coach our youth and masters biathletes. Two of his boys are currently active in our programs and you can find Matt occasionally jumping in to a biathlon event demonstrating skills he learned during his years with the guard."
        )
        matt.save()
        ben = Coach(
            last_name="Paradis",
            first_name="Ben",
            title="Youth and Masters Nordic Coach",
            img_url="https://cdn.fortkentoc.org/programs/coach_photos/fort-kent-outdoor-center-coach-ben-paradis.png",
            profile="Ben Paradis has been coaching Nordic skiing for over 30 years and has never had a bad day skiing. No matter what, skiing puts a smile on his face. Ben is especially adept at analyzing and explaining technique to all age levels, and you will surely come back from a refreshing ski in the brisk air with a smile on your face!"
        )
        ben.save()
        sarah = Coach(
            last_name="Ashley",
            first_name="Sarah",
            title="",
            img_url="https://cdn.fortkentoc.org/programs/coach_photos/fort-kent-outdoor-center-coach-sarah-ashley.jpg",
            profile="Sarah Ashley is our wonderful middle school and ladies night coach who is an alumni of our high school ski team and she always finds a way to instill and have have fun out in the ski trails with a smile on her face!"
        )
        sarah.save()

    operations = [
        migrations.RunPython(populate_coaching_staff)
    ]