# Generated by Django 4.2.6 on 2023-11-12 00:06

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_delete_boardmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="whowearepage",
            name="board_members",
            field=wagtail.fields.StreamField(
                [
                    (
                        "board_member",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.StructBlock(
                                [
                                    (
                                        "last_name",
                                        wagtail.blocks.CharBlock(
                                            label="Last Name", required=True
                                        ),
                                    ),
                                    (
                                        "first_name",
                                        wagtail.blocks.CharBlock(
                                            label="First Name", required=True
                                        ),
                                    ),
                                    (
                                        "title",
                                        wagtail.blocks.CharBlock(
                                            label="Title", required=False
                                        ),
                                    ),
                                    (
                                        "img",
                                        wagtail.images.blocks.ImageChooserBlock(
                                            label="Image", required=False
                                        ),
                                    ),
                                    (
                                        "profile",
                                        wagtail.blocks.CharBlock(
                                            label="Profile", required=False
                                        ),
                                    ),
                                ]
                            )
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
