# Generated by Django 4.2.6 on 2023-11-10 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_testimonial_alter_coach_slug"),
    ]

    def add_initial_testimonial(apps, schema_editor):
        testimonial = """
            <p class='my-4'>Fort Kent Outdoor Center has truly transformed over the years from a world-class training center for Nordic and Biathlon athletes to a dynamic 4-season venue for all ages. As a proud member of this special community, I've witnessed the evolution of FKOC into a gem that offers an array of outdoor experiences.</p>

            <p class='my-4'>From hosting national and international events to now providing opportunities for cross-country skiing, snowshoeing, mountain biking, hiking, roller skiing, orienteering skills development, walking, and even disk golf – FKOC has become a hub for outdoor enthusiasts in rural Maine.</p>

            <p class='my-4'>Join us at FKOC and discover the beauty of this community and the diverse outdoor adventures it offers. It's a place we proudly call home, and I invite you to be part of the experience!</p>
            """

        Testimonial = apps.get_model('website', 'Testimonial')
        testimonial = Testimonial(
            author="Alain Ouellette",
            title="From Athletes to Adventurers",
            testimonial=testimonial
        )
        testimonial.save()

        brandon_testimonial = ("<p class='my-4'>The Fort Kent Outdoor Center was a deciding factor fo my partner and I to move to the area.  We visited the outdoor center as a guest a few times and enjoyed the facilities and trails so much, it made us want to move to the region.</p>"
                               "<p class='my-4'>My partner and I have greatly enjoyed membership at the FKOC and getting to know other members.</p>")
        testimonial = Testimonial(
            author="Brandon Goding",
            title="New to The Area",
            testimonial=brandon_testimonial
        )
        testimonial.save()
    operations = [
        migrations.RunPython(add_initial_testimonial)
    ]
