# Generated by Django 4.2.6 on 2023-11-12 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_auto_20231112_2150"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coach",
            name="img_url",
        ),
    ]
