# Generated by Django 4.2.6 on 2023-11-12 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_whowearepage_board_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="whowearepage",
            old_name="board_members",
            new_name="body",
        ),
    ]
