# Generated by Django 4.2.6 on 2023-11-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_auto_20231110_1307"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(max_length=50)),
                ("teaser", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("img_url", models.URLField(blank=True)),
            ],
        ),
    ]
