# Generated by Django 4.2.6 on 2023-11-11 02:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_event"),
    ]

    def add_initial_events(apps, schema_editor):

        season_ski_rental_pickup = "<p><strong>Get Ready for Ski Season at Fort Kent Outdoor Center!</strong></p><p><strong>Seasonal Ski Rentals</strong></p><p>Gear up for winter fun! Fort Kent Outdoor Center is excited to offer seasonal ski rentals exclusively for FKOC members. Join us on Saturday, November 18, and Sunday, December 3, from 1:00 to 3:00 PM to secure your ski equipment for the season. To participate, make sure you have a 2024 Membership. Prices for the 2024 season rentals are as follows:</p><ul><li><strong>Adult (19 yrs old+):</strong> $120</li><li><strong>Youth (7-18 yrs old):</strong> $80</li><li><strong>Child (<7 yrs old):</strong> $50</li></ul><p>Not a member yet? No worries! You can purchase your 2024 Membership in person on the rental dates. If you prefer the convenience of online registration, our website will be up and running by December 1st. Until then, payment by check is recommended. Simply print the membership form from our website, or grab one at the lodge during the rental events.</p><p><a href='https://www.fortkentoc.org/memberships/'>Visit our Memberships Page</a></p>"

        Event = apps.get_model('website', 'Event')
        Event.objects.create(
            title="Season Ski Rental Pickup",
            date="2023-11-18",
            start_time="13:00",
            end_time="15:00",
            location="FKOC Base Lodge",
            teaser="Gear up for winter fun with our Seasonal Ski Rentals!",
            description=season_ski_rental_pickup,
            img_url="",
        )
        Event.objects.create(
            title="Season Ski Rental Pickup",
            date="2023-12-3",
            start_time="13:00",
            end_time="15:00",
            location="FKOC Base Lodge",
            teaser="Gear up for winter fun with our Seasonal Ski Rentals!",
            description=season_ski_rental_pickup,
            img_url="",
        )

        welcome_winter = "<header><h1>Embrace Winter Magic at Our Welcome Winter Celebration!</h1></header><section><p>Join us on December 2nd, from 5:00 to 8:00 PM, for a heartwarming Welcome Winter Celebration. This special eventmarks the beginning of the winter season, filled with community spirit and festive joy.</p></section><section><h2>Event Highlights:</h2><ol><li><strong>Board Member Elections:</strong> Be a part of our community's future by participating in the election of new board members. Your vote shapes the direction of our center and the experiences we offer.</li><li><strong>Membership Opportunities:</strong> Elevate your connection with the Fort Kent Outdoor Center bysecuring your 2024 membership. While there are no discounts, your membership ensures a year of outdooradventures and shared moments with fellow enthusiasts.</li><li><strong>Casual Refreshments:</strong> Enjoy a relaxed atmosphere with simple and comforting refreshments.A casual cash bar will be available for your beverage preferences, adding a touch of warmth to thecelebration.</li></ol></section><section><h2>Save the Date:</h2><p><strong>Date:</strong> December 2nd<br><strong>Time:</strong> 5:00 PM – 8:00 PM</p></section><section><p>Come together with friends and family to celebrate the season, share stories, and embrace the winter spirit.We look forward to welcoming winter with you at [Your Center's Name].</p></section>"

        Event.objects.create(
            title="Join Us for a Spectacular Welcome Winter Celebration!",
            date="2023-12-2",
            start_time="17:00",
            end_time="20:00",
            location="FKOC Base Lodge",
            teaser="As the winter winds start to whisper, we invite you to our enchanting Welcome Winter Celebration on December 2nd, from 5:00 to 8:00 PM. ",
            description=welcome_winter,
            img_url="",
        )

    operations = [
        migrations.RunPython(add_initial_events)
    ]