# Generated by Django 4.2.6 on 2023-11-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0007_remove_coach_img_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="img",
            field=models.ImageField(null=True, upload_to="coaches"),
        ),
    ]
