# Generated by Django 4.2.6 on 2023-11-12 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_coach_img"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmember",
            options={
                "verbose_name": "Board Member",
                "verbose_name_plural": "Board Members",
            },
        ),
        migrations.AlterModelOptions(
            name="coach",
            options={
                "verbose_name": "Coach",
                "verbose_name_plural": "Coaches",
            },
        ),
        migrations.RemoveField(
            model_name="boardmember",
            name="img",
        ),
    ]
