# Generated by Django 4.2.6 on 2023-11-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_coach_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name="coach",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Leave blank to auto-generate slug.",
                null=True,
            ),
        ),
    ]
