# Generated by Django 4.2.6 on 2023-11-13 01:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_coach_img"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
