# Generated by Django 4.2.6 on 2023-11-18 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0013_eventlistingpage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventcategory",
            old_name="category",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="eventtags",
            old_name="tag",
            new_name="title",
        ),
    ]
