# Generated by Django 4.2.6 on 2023-11-18 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0017_eventtags_color_class"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventTags",
            new_name="EventTag",
        ),
    ]
