# Generated by Django 4.2.6 on 2023-11-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0020_alter_eventcategory_color_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventcategory",
            name="color_class",
            field=models.CharField(
                choices=[
                    ("gray", "Gray"),
                    ("red", "Red"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                ],
                default="gray",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="eventtag",
            name="color_class",
            field=models.CharField(
                choices=[
                    ("gray", "Gray"),
                    ("red", "Red"),
                    ("yellow", "Yellow"),
                    ("green", "Green"),
                    ("blue", "Blue"),
                    ("purple", "Purple"),
                    ("pink", "Pink"),
                ],
                default="gray",
                max_length=7,
            ),
        ),
    ]
