# Generated by Django 4.2.6 on 2023-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0023_eventpage_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="date",
            field=models.DateField(help_text="Enter the date of the event."),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="end_time",
            field=models.TimeField(
                help_text="Leave blank if event does not have a specific end time."
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="start_time",
            field=models.TimeField(
                help_text="Enter the start time of the event."
            ),
        ),
    ]
