# Generated by Django 4.2.6 on 2023-11-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "website",
            "0024_alter_eventpage_date_alter_eventpage_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventpage",
            name="end_time",
            field=models.TimeField(
                blank=True,
                help_text="Leave blank if event does not have a specific end time.",
                null=True,
            ),
        ),
    ]
