# Generated by Django 4.2.6 on 2023-11-18 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0025_alter_eventpage_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventpage",
            name="date",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="eventpage",
            name="start_time",
        ),
    ]
