# Generated by Django 4.2.6 on 2023-11-19 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0040_policiespage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BoardMember",
        ),
    ]
