# Generated by Django 4.2.6 on 2023-11-19 02:29

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0042_boardmember"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="boardmember",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Board Member",
                "verbose_name_plural": "Board Members",
            },
        ),
        migrations.AlterField(
            model_name="boardmember",
            name="page",
            field=modelcluster.fields.ParentalKey(
                default=9,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_members",
                to="website.aboutpage",
            ),
        ),
    ]
