# Generated by Django 4.2.6 on 2023-11-20 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("website", "0045_alter_coach_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivitiesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.AlterModelOptions(
            name="coach",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Coach",
                "verbose_name_plural": "Coaches",
            },
        ),
    ]
