WINTER_SEASON = "winter_season"
OFF_SEASON = "off_season"


ACTIVITIES = [
    {
        "name": "Biathlon",
        "slug": "biathlon",
        "thumbnail": "/static/media/public/images/winter-biathlon-skier.2e16d0ba.fill-584x238.jpg",
        "imgLeft": "/static/media/public/images/winter-biathlon-shooting-range.2e16d0ba.fill-284x394.jpg",
        "imgRight": "/static/media/public/images/winter-biathlon-skier.2e16d0ba.fill-284x394.jpg",
        "description": "Biathlon, a two phase athletic pursuit is typically practiced in the summertime using Roller Skis on the paved trails through the Stadium at the Fort Kent Outdoor Center. The athlete will stop and shoot at the targets in the range that is set up in the Stadium. Biathletes must be in a program or have permission in order to shoot on the range. For more information please contact Carl Theriault at theriault.carl@hotmail.com",
        "col_span": 2,
        "season": WINTER_SEASON,
    },
    {
        "name": "Cross Country Skiing",
        "slug": "cross-country-skiing",
        "thumbnail": "/static/media/public/images/crosscountryskiing.2e16d0ba.fill-284x238.jpg",
        "imgLeft": "/static/media/public/images/fort-kent-outdoor-center-coach-ben.2e16d0ba.fill-284x394.png",
        "imgRight": "/static/media/public/images/crosscountryskiing.2e16d0ba.fill-284x394.jpg",
        "description": "As one of the first ski centers in the Northeast to have snow in the fall and the last to hang up our skis in April, plus a fantastic grooming crew, the Fort Kent Outdoor Center is becoming the No.1 choice for cross country skiing. Come check out our trails!",
        "col_span": 1,
        "season": WINTER_SEASON,
    },
    {
        "name": "Snowshoeing",
        "slug": "snowshoeing",
        "thumbnail": "/static/media/public/images/snowshoes.2e16d0ba.fill-284x238.jpg",
        "imgLeft": "/static/media/public/images/snowshoeing.2e16d0ba.fill-284x394.jpg",
        "imgRight": "/static/media/public/images/snowshoes.2e16d0ba.fill-284x394.jpg",
        "description": "We currently have seven miles of snowshoe trails surrounding the venue. They range from easy and rolling to those that are steeper and more difficult. Many of the trails interconnect, allowing for outings of varying lengths. The trails can be accessed at three of our trailheads: FKOC, Red Barn and Lonesome Pine Trails. Grab a map or access it on your smartphone and follow the yellow snowshoe signs. The trail intersections are numbered and have directional signs to make the trails easy to navigate.",
        "col_span": 1,
        "season": WINTER_SEASON,
    },
    {
        "name": "Sledding",
        "slug": "sledding",
        "thumbnail": "/static/media/public/images/kids-sledding.2e16d0ba.fill-284x238.jpg",
        "imgLeft": "/static/media/public/images/fort-kent-outdoor-center-coach-ben.2e16d0ba.fill-284x394.png",
        "imgRight": "/static/media/public/images/kids-sledding.2e16d0ba.fill-284x394.jpg",
        "description": "Indulge in the exhilaration of winter fun at Fort Kent Outdoor Center as we present an exciting sledding experience for enthusiasts of all ages. Nestled within our winter wonderland, our specially crafted sledding hill promises thrills and laughter against a backdrop of snowy enchantment. Whether you're a family seeking a memorable day of winter bonding or an adventure seeker craving the rush of the downhill slide, our sledding hill is the perfect destination. Feel the crisp winter air on your face as you glide effortlessly down the slope, surrounded by the beauty of a snow-covered landscape. With safety as our priority, our well-maintained hill ensures a delightful sledding escapade for everyone. Join us in embracing the magic of winter and create cherished memories on our inviting sledding hill – where the joy of the season comes alive with every descent.",
        "col_span": 1,
        "season": WINTER_SEASON,
    },
    {
        "name": "Skijoring",
        "slug": "skijoring",
        "thumbnail": "/static/media/public/images/skijoring.2e16d0ba.fill-584x238.jpg",
        "imgLeft": "/static/media/public/images/skijoring-set-up.2e16d0ba.fill-284x394.jpg",
        "imgRight": "/static/media/public/images/skijoring.2e16d0ba.fill-284x394.jpg",
        "description": "Embark on a winter adventure with skijoring, a thrilling sport that combines the joy of skiing with the energy and enthusiasm of your four-legged companion. Skijoring involves being harnessed to a dog, creating a harmonious partnership as you navigate snowy landscapes together. This exciting activity has gained popularity among dog lovers seeking an active and unique way to enjoy the winter months. At Fort Kent Outdoor Center, we celebrate the spirit of skijoring and the bond it fosters between humans and their canine friends. Explore the beauty of winter landscapes, feel the rush of the chilly breeze, and experience the joy of gliding across snow-covered trails in this exhilarating fusion of sport and companionship. Discover the wonders of skijoring and the special connection it brings to winter enthusiasts and their furry companions.",
        "col_span": 2,
        "season": WINTER_SEASON,
    },
    {
        "name": "No Snow Biathlon",
        "slug": "no-snow-biathlon",
        "thumbnail": "/static/media/public/images/skijoring.2e16d0ba.fill-584x238.jpg",
        "imgLeft": "/static/media/public/images/skijoring-set-up.2e16d0ba.fill-284x394.jpg",
        "imgRight": "/static/media/public/images/skijoring.2e16d0ba.fill-284x394.jpg",
        "description": "Biathlon combines the sports of cross country skiing and marksmanship. A sport that started as a military exercise and strategy in Scandinavia is now an Olympic event. In the summer months Biathlon is typically practiced using Roller Skis on the paved trails through the Stadium at the Fort Kent Outdoor Center. The athlete will stop and shoot at the targets in the range that is set up in the Stadium. Biathletes must be in a program or have permission from Carl Theriault in order to shoot on the range.",
        "col_span": 1,
        "season": OFF_SEASON,
    },
    {
        "name": "Disc Golf",
        "slug": "disc-golf",
        "thumbnail": "/static/media/public/images/skijoring.2e16d0ba.fill-584x238.jpg",
        "imgLeft": "/static/media/public/images/skijoring-set-up.2e16d0ba.fill-284x394.jpg",
        "imgRight": "/static/media/public/images/skijoring.2e16d0ba.fill-284x394.jpg",
        "description": "Similar to the sport of golf, disc golf involves frisbee-like equipment including a driver, a mid-range, and a putter being thrown into a metal basket. FKOC offers an 18-hole disc golf course that meanders through a variety of snowshoe, bike, and ski trails. Disc golfers can rent discs at the Disc Golf Kiosk located on the outside of the lodge, or they can bring their own. You can find our disc golf map on the UDisc App, or you can print our course map. The price of a round of disc golf is $5.00 per person, or it’s free for those with an annual membership.",
        "col_span": 2,
        "season": OFF_SEASON,
    },
    {
        "name": "Orienteering",
        "slug": "orienteering",
        "thumbnail": "/static/media/public/images/skijoring.2e16d0ba.fill-584x238.jpg",
        "imgLeft": "/static/media/public/images/skijoring-set-up.2e16d0ba.fill-284x394.jpg",
        "imgRight": "/static/media/public/images/skijoring.2e16d0ba.fill-284x394.jpg",
        "description": "By definition, orienteering is a race in which participants use a highly detailed map and possibly a compass to navigate their way between checkpoints along an unfamiliar course. On an orienteering course, individuals can strengthen their map reading skills and groups can strengthen their team-building, all while enjoying the great outdoors. Beginner and Intermediate courses are available! Great for youth and adult groups! For more information, or to schedule your group event, email info@fortkentoc.org or message us on Facebook!",
        "col_span": 1,
        "season": OFF_SEASON,
    },
    {
        "name": "Running",
        "slug": "running",
        "thumbnail": "/static/media/public/images/skijoring.2e16d0ba.fill-584x238.jpg",
        "imgLeft": "/static/media/public/images/skijoring-set-up.2e16d0ba.fill-284x394.jpg",
        "imgRight": "/static/media/public/images/skijoring.2e16d0ba.fill-284x394.jpg",
        "description": "We have many trails that are good for running! Our new Mountain Bike trails have excellent footing and if you would like hills for endurance training there are too many to count! Many local runners start at Lonesome Pine Trails and take the “Green Bean” Trails up to the FKOC trails. There are also well marked paved trails that start at the Main Parking Lot and for the adventurous there are numerous directions you can go on wider nordic skiing trails and wooded snowshoe trails. Non-Members may pay a trail fee in the Donation Box located in the FKOC parking lot or you can buy a “day pass” for the trails using the link below.",
        "col_span": 1,
        "season": OFF_SEASON,
    },
    {
        "name": "Rollerskiing",
        "slug": "rollerskiing",
        "thumbnail": "/static/media/public/images/skijoring.2e16d0ba.fill-584x238.jpg",
        "imgLeft": "/static/media/public/images/skijoring-set-up.2e16d0ba.fill-284x394.jpg",
        "imgRight": "/static/media/public/images/skijoring.2e16d0ba.fill-284x394.jpg",
        "description": "",
        "col_span": 1,
        "season": OFF_SEASON,
    },
    {
        "name": "Biking",
        "slug": "biking",
        "thumbnail": "/static/media/public/images/skijoring.2e16d0ba.fill-584x238.jpg",
        "imgLeft": "/static/media/public/images/skijoring-set-up.2e16d0ba.fill-284x394.jpg",
        "imgRight": "/static/media/public/images/skijoring.2e16d0ba.fill-284x394.jpg",
        "description": "Bring the whole family for an easy ride on the paved loop or we have an Intermediate route for those who want a little more challenge on grassy trails. Please yield to roller skiers, walkers and horses. Our MOUNTAIN BIKE single track trails are amazing, there are many trails geared for beginner, to advanced bikers. Some trails are currently under construction but there are already 3.7 miles of Mountain bike specific trails ready to ride, in addition to our 20+ miles of regular trails.",
        "col_span": 2,
        "season": OFF_SEASON,
    },
    {
        "name": "Walking & Hiking",
        "slug": "walking-and-hiking",
        "thumbnail": "/static/media/public/images/skijoring.2e16d0ba.fill-584x238.jpg",
        "imgLeft": "/static/media/public/images/skijoring-set-up.2e16d0ba.fill-284x394.jpg",
        "imgRight": "/static/media/public/images/skijoring.2e16d0ba.fill-284x394.jpg",
        "description": "In the spring, summer and fall, our ski and snowshoe trails become our walking and hiking trails. All the trails are accessible from the FKOC venue. All of our 17 miles of ski trails are open for walking/running, but only 12 miles are paved or mowed and on dry ground. The seven miles of snowshoeing trails provide excellent hiking opportunities. We have a series of Diamond Trails, which are marked with colored diamonds. These utilize the paved trails, grass ski trails and woodsy snowshoe trails. Each trail lists its length, degree of difficulty and approximate time to complete. Sturdy shoes are recommended.",
        "col_span": 2,
        "season": OFF_SEASON,
    },
]
