# Generated by Django 5.2.5 on 2025-08-17 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="stripe_customer_id",
        ),
    ]
