# Generated by Django 5.2.5 on 2025-08-17 21:47

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_stripecustomer"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="uniq_customer_email_ci",
            ),
        ),
    ]
