# Generated by Django 5.2.5 on 2025-08-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_customer_uniq_customer_email_ci"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("product_type", models.CharField(blank=True, max_length=20)),
                ("shippable", models.BooleanField(default=False)),
                ("images", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["active"], name="billing_pro_active_747cf6_idx"
                    ),
                    models.Index(
                        fields=["name"], name="billing_pro_name_a6565e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("currency", models.CharField(default="usd", max_length=10)),
                (
                    "unit_amount",
                    models.IntegerField(
                        help_text="Amount in the smallest currency unit (e.g., cents)"
                    ),
                ),
                ("type", models.CharField(default="one_time", max_length=20)),
                (
                    "recurring_interval",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "recurring_interval_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "trial_period_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("tax_behavior", models.CharField(blank=True, max_length=20)),
                ("livemode", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="billing.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["active"], name="billing_pri_active_8d1ffb_idx"
                    ),
                    models.Index(
                        fields=["currency"],
                        name="billing_pri_currenc_8116ba_idx",
                    ),
                    models.Index(
                        fields=["type"], name="billing_pri_type_46b5ba_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("type", "one_time"),
                            models.Q(
                                ("type", "recurring"),
                                ("recurring_interval__gt", ""),
                                ("recurring_interval_count__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="price_recurring_fields_valid",
                    )
                ],
            },
        ),
    ]
