# Generated by Django 4.2.6 on 2024-01-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivitiesEnjoyed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name="membership",
            name="activities_enjoyed",
            field=models.ManyToManyField(
                blank=True, null=True, to="membership.activitiesenjoyed"
            ),
        ),
    ]
